CREATE DATABASE DENIS_TREINAMENTO_LANHOUSE;

USE DENIS_TREINAMENTO_LANHOUSE;

CREATE TABLE DEFEITOS(
	ID INT PRIMARY KEY IDENTITY(1,1), /*O primeiro id é 1, o segundo será 2, o terceiro será 3 e assim por diante*/
	NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_EQUIPAMENTOS(
	ID INT PRIMARY KEY IDENTITY(1,1), /*1,1 não precisaria ser colocado, pois é default*/
	NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE REGISTROS_DEFEITOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DATA_DEFEITO DATETIME NOT NULL,
	TIPO_EQUIPAMENTO_ID INT NOT NULL,
	DEFEITO_ID INT NOT NULL,
	OBSERVACAO VARCHAR(300),
	FOREIGN KEY(TIPO_EQUIPAMENTO_ID) REFERENCES TIPOS_EQUIPAMENTOS(ID),
	FOREIGN KEY(DEFEITO_ID) REFERENCES DEFEITOS(ID),
);

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(50) NOT NULL
);

